# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

target 'MeeroApp' do
  source 'https://github.com/Rayshawn/LXSpecs.git'
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for MeeroApp
  pod 'LXToolsModules', '~> 0.2.0'
end
